<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
	<title></title>
</head>
<body>
<h1>Ma TODOLIST</h1>
<div id="list">
	
</div>
<hr>
 <form action="todolist.php" method="POST">
 	<input type="submit" name="supp" value="supp">
 	<h2>Nouvelle Tache</h2>
 	Titre 		: <input type="text" name="titre"><br><br>
 	Description :<textarea name="desc"></textarea><br><br>
 	Date de fin	:<input type="date" name="date"><br><br>
 	Priorité	:<input type="radio" name="Prior" value="Basse" checked> Basse 
 	  <input type="radio" name="Prior" value="normal" checked> Normal 
 	  <input type="radio" name="Prior" value="haute" checked> Haute 
 	  <input type="submit" name="Envoyer" value="Enregistrer">  

 </form>
</body>
</html>
